### ISSUE TITLE
High Sierra - Xcode 9.3

### ISSUE THREAD

**Issue by Pat-PandaTech** [workflowproducts/libpq-ios#1]
This script appears to be broken when run against High Sierra and Xcode 9.3

I've attached my config.log file to highlight the problem (C Compiler Cannot Create Executables).  

[config.log](https://github.com/workflowproducts/libpq-ios/files/1983947/config.log)

**Comment by nunziotocci** [comment]
Please download the latest version and try it again.

**Comment by Pat-PandaTech** [comment]
Now compiles for PostgreSQL 9.6.2.  Thanks
