### ISSUE TITLE
Script doesn't work against PostgreSQL 10.3

### ISSUE THREAD

**Issue by Pat-PandaTech** [workflowproducts/libpq-ios#2]
When I try to compile against PostgreSQL 10.3 I get the attached errors.

(BTW - do you have any links to help me understand the make process so I can better debug scripts like this as I'd like to contribute - thanks)

<img width="616" alt="screen shot 2018-05-09 at 09 50 43" src="https://user-images.githubusercontent.com/4303817/39805408-b0989a70-536e-11e8-8ef0-ff4e6362130d.png">
[config.log](https://github.com/workflowproducts/libpq-ios/files/1987057/config.log)

**Comment by nunziotocci** [comment]
It appears that newer version of postgres use /dev/urandom for random numbers if no OpenSSL is found.

Unfortunately for us, when I originally wrote this script, I was having trouble with compiling OpenSSL for ARM. So, I can either disable strong random numbers (I'd prefer not), or I can see about OpenSSL for ARM again.

> do you have any links to help me understand the make process

I don't have anything specific to recommend for postgres' autoconf system. But, all I'm doing in this repo, is maintaining one script that downloads postgres and cross-compiles one component.
It's a fairly straightforward script, but it could use some comments for those less familiar with autoconf.

I'm going to look into adding OpenSSL, and I'll comment the script better.

**Comment by nunziotocci** [comment]
Ok, I've added LibreSSL and it now compiles and runs libpq from postgresql 10.3 (now the default).

I also added some comments to the build script. if you have any particular questions about the build process, please [email me](mailto:nunzio@workflowproducts.com) and I'll see what I can do.
